# Generated by Django 4.1 on 2024-05-16 10:11

import adv.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("pub_date", models.DateField(verbose_name="date published")),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("platform", models.CharField(max_length=20)),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("Photo", models.ImageField(blank=True, upload_to="adv_images")),
            ],
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("pub_date", models.DateField(verbose_name="date published")),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("Photo", models.ImageField(blank=True, upload_to="Club_images")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("job", models.CharField(max_length=20)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "男"), ("F", "女")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("photo", models.ImageField(blank=True, upload_to="User_images")),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", adv.fields.CompositeField()),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Comments",
                        to="adv.user",
                    ),
                ),
                (
                    "adv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Comments_set",
                        to="adv.adv",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="adv",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="adv.club"
            ),
        ),
    ]
