# Generated by Django 4.1 on 2024-05-16 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adv", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adv",
            old_name="Photo",
            new_name="photo",
        ),
        migrations.RenameField(
            model_name="club",
            old_name="Photo",
            new_name="photo",
        ),
    ]
