# Generated by Django 4.1 on 2024-05-16 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adv", "0002_rename_photo_adv_photo_rename_photo_club_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="User",
            new_name="user",
        ),
    ]
